server:
 port: 9091

spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/CitizenDB
  username: postgres
  password: Root@123
  driver-class: org.postgresql.driver

 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect


